# This is a basic workflow to help you get started with Actions

name: CI 4 Singularity Container of ACES

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    ENV_NAME:        casacore
    PYTHON_VERSION:  3.12

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Ensure that conda is available
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""

      # Simple conda checks:
      - name: "Setup CONDA for CASACORE"
        run: |
         conda create -c conda-forge -n ${{ env.ENV_NAME }} python=${{ env.PYTHON_VERSION }} -y
         conda init
         source ~/.bashrc
         conda activate ${{ env.ENV_NAME }}
         conda install -c conda-forge casacore compilers boost -y
         pip install uv
         uv pip install python-casacore
         echo "============================= TESTING CASCORE INSTALL =========================="
         python -c "from casacore.tables import table"
         python -c "import numpy"
         echo "=============================      END TESTING        =========================="

      # Install aces:
      - name: "Install ACES"
        run: |
         # Checkout aces
         git clone https://bitbucket.csiro.au/scm/aces/aces-apps.git
         
         cd aces-apps

         # Now pip install the askap dependencies
         pip install -r askap-requirements.txt

         # Now pip install the cloned aces-app into the virtual environment
         pip install -e `pwd`

# Return to the initial directory
cd ${START_DIR}


      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
